config/routes.rb
Rails.application.routes.draw do
  resources :results
  resources :student_answers
  resources :question_papers
  resources :questions
  resources :answers
  resources :exams
  resources :subjects
  resources :attendances
  resources :students
  resources :class_infos

  root 'class_infos#index'
  get 'students/index'
  get 'students/list'
  post 'students/create'
  get 'attendances/index'
  get 'attendances/list'
  post 'attendances/create'
  get 'attendances/show'
  post 'attendances/showClassStudents'
  
end

app/models/class_info.rb
class ClassInfo < ActiveRecord::Base
end

app/controllers/class_infos_controller.rb
class ClassInfosController < ApplicationController
  before_action :set_class_info, only: [:show, :edit, :update, :destroy]

  # GET /class_infos
  # GET /class_infos.json
  def index
    @class_infos = ClassInfo.all
  end

  # GET /class_infos/1
  # GET /class_infos/1.json
  def show
  end

  # GET /class_infos/new
  def new
    @class_info = ClassInfo.new
  end

  # GET /class_infos/1/edit
  def edit
  end

  # POST /class_infos
  # POST /class_infos.json
  def create
    @class_info = ClassInfo.new(class_info_params)

    respond_to do |format|
      if @class_info.save
        format.html { redirect_to @class_info, notice: 'Class info was successfully created.' }
        format.json { render :show, status: :created, location: @class_info }
      else
        format.html { render :new }
        format.json { render json: @class_info.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /class_infos/1
  # PATCH/PUT /class_infos/1.json
  def update
    respond_to do |format|
      if @class_info.update(class_info_params)
        format.html { redirect_to @class_info, notice: 'Class info was successfully updated.' }
        format.json { render :show, status: :ok, location: @class_info }
      else
        format.html { render :edit }
        format.json { render json: @class_info.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /class_infos/1
  # DELETE /class_infos/1.json
  def destroy
    @class_info.destroy
    respond_to do |format|
      format.html { redirect_to class_infos_url, notice: 'Class info was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_class_info
      @class_info = ClassInfo.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def class_info_params
      params.require(:class_info).permit(:name)
    end
end

app/helpers/class_infos_helper.rb
module ClassInfosHelper
end

app/views/class_infos/_form.html.erb
<%= form_for(@class_info) do |f| %>
  <% if @class_info.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@class_info.errors.count, "error") %> prohibited this class_info from being saved:</h2>

      <ul>
      <% @class_info.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/class_infos/edit.html.erb
<h1>Editing Class Info</h1>

<%= render 'form' %>

<%= link_to 'Show', @class_info %> |
<%= link_to 'Back', class_infos_path %>

app/views/class_infos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Class Infos</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @class_infos.each do |class_info| %>
      <tr>
        <td><%= class_info.name %></td>
        <td><%= link_to 'Show', class_info %></td>
        <td><%= link_to 'Edit', edit_class_info_path(class_info) %></td>
        <td><%= link_to 'Destroy', class_info, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Class info', new_class_info_path %>

app/views/class_infos/new.html.erb
<h1>New Class Info</h1>

<%= render 'form' %>

<%= link_to 'Back', class_infos_path %>

app/views/class_infos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @class_info.name %>
</p>

<%= link_to 'Edit', edit_class_info_path(@class_info) %> |
<%= link_to 'Back', class_infos_path %>