config/routes.rb
Rails.application.routes.draw do
  resources :results
  resources :student_answers
  resources :question_papers
  resources :questions
  resources :answers
  resources :exams
  resources :subjects
  resources :attendances
  resources :students
  resources :class_infos

  root 'class_infos#index'
  get 'students/index'
  get 'students/list'
  post 'students/create'
  get 'attendances/index'
  get 'attendances/list'
  post 'attendances/create'
  get 'attendances/show'
  post 'attendances/showClassStudents'
  
end

app/models/answer.rb
class Answer < ActiveRecord::Base
end

app/models/attendance.rb
class Attendance < ActiveRecord::Base
end

app/models/class_info.rb
class ClassInfo < ActiveRecord::Base
end

app/models/exam.rb
class Exam < ActiveRecord::Base
end

app/models/question.rb
class Question < ActiveRecord::Base
end

app/models/question_paper.rb
class QuestionPaper < ActiveRecord::Base
end

app/models/result.rb
class Result < ActiveRecord::Base
end

app/models/student.rb
class Student < ActiveRecord::Base
end

app/models/student_answer.rb
class StudentAnswer < ActiveRecord::Base
end

app/models/subject.rb
class Subject < ActiveRecord::Base
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  before_action :set_answer, only: [:show, :edit, :update, :destroy]

  # GET /answers
  # GET /answers.json
  def index
    @answers = Answer.all
  end

  # GET /answers/1
  # GET /answers/1.json
  def show
  end

  # GET /answers/new
  def new
    @answer = Answer.new
  end

  # GET /answers/1/edit
  def edit
  end

  # POST /answers
  # POST /answers.json
  def create
    @answer = Answer.new(answer_params)

    respond_to do |format|
      if @answer.save
        format.html { redirect_to @answer, notice: 'Answer was successfully created.' }
        format.json { render :show, status: :created, location: @answer }
      else
        format.html { render :new }
        format.json { render json: @answer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /answers/1
  # PATCH/PUT /answers/1.json
  def update
    respond_to do |format|
      if @answer.update(answer_params)
        format.html { redirect_to @answer, notice: 'Answer was successfully updated.' }
        format.json { render :show, status: :ok, location: @answer }
      else
        format.html { render :edit }
        format.json { render json: @answer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /answers/1
  # DELETE /answers/1.json
  def destroy
    @answer.destroy
    respond_to do |format|
      format.html { redirect_to answers_url, notice: 'Answer was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_answer
      @answer = Answer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def answer_params
      params.require(:answer).permit(:text)
    end
end

app/controllers/exams_controller.rb
class ExamsController < ApplicationController
  before_action :set_exam, only: [:show, :edit, :update, :destroy]

  # GET /exams
  # GET /exams.json
  def index
    @exams = Exam.all
  end

  # GET /exams/1
  # GET /exams/1.json
  def show
  end

  # GET /exams/new
  def new
    @exam = Exam.new
  end

  # GET /exams/1/edit
  def edit
  end

  # POST /exams
  # POST /exams.json
  def create
    @exam = Exam.new(exam_params)

    respond_to do |format|
      if @exam.save
        format.html { redirect_to @exam, notice: 'Exam was successfully created.' }
        format.json { render :show, status: :created, location: @exam }
      else
        format.html { render :new }
        format.json { render json: @exam.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /exams/1
  # PATCH/PUT /exams/1.json
  def update
    respond_to do |format|
      if @exam.update(exam_params)
        format.html { redirect_to @exam, notice: 'Exam was successfully updated.' }
        format.json { render :show, status: :ok, location: @exam }
      else
        format.html { render :edit }
        format.json { render json: @exam.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /exams/1
  # DELETE /exams/1.json
  def destroy
    @exam.destroy
    respond_to do |format|
      format.html { redirect_to exams_url, notice: 'Exam was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_exam
      @exam = Exam.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def exam_params
      params.require(:exam).permit(:ExamDate)
    end
end

app/controllers/question_papers_controller.rb
class QuestionPapersController < ApplicationController
  before_action :set_question_paper, only: [:show, :edit, :update, :destroy]

  # GET /question_papers
  # GET /question_papers.json
  def index
    @question_papers = QuestionPaper.all
  end

  # GET /question_papers/1
  # GET /question_papers/1.json
  def show
  end

  # GET /question_papers/new
  def new
    @question_paper = QuestionPaper.new
  end

  # GET /question_papers/1/edit
  def edit
  end

  # POST /question_papers
  # POST /question_papers.json
  def create
    @question_paper = QuestionPaper.new(question_paper_params)

    respond_to do |format|
      if @question_paper.save
        format.html { redirect_to @question_paper, notice: 'Question paper was successfully created.' }
        format.json { render :show, status: :created, location: @question_paper }
      else
        format.html { render :new }
        format.json { render json: @question_paper.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /question_papers/1
  # PATCH/PUT /question_papers/1.json
  def update
    respond_to do |format|
      if @question_paper.update(question_paper_params)
        format.html { redirect_to @question_paper, notice: 'Question paper was successfully updated.' }
        format.json { render :show, status: :ok, location: @question_paper }
      else
        format.html { render :edit }
        format.json { render json: @question_paper.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /question_papers/1
  # DELETE /question_papers/1.json
  def destroy
    @question_paper.destroy
    respond_to do |format|
      format.html { redirect_to question_papers_url, notice: 'Question paper was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_question_paper
      @question_paper = QuestionPaper.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def question_paper_params
      params.require(:question_paper).permit(:examid, :questionid)
    end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/attendances_helper.rb
module AttendancesHelper
end

app/helpers/class_infos_helper.rb
module ClassInfosHelper
end

app/helpers/exams_helper.rb
module ExamsHelper
end

app/helpers/question_papers_helper.rb
module QuestionPapersHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/results_helper.rb
module ResultsHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/helpers/subjects_helper.rb
module SubjectsHelper
end

app/views/question_papers/_form.html.erb
<%= form_for(@question_paper) do |f| %>
  <% if @question_paper.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@question_paper.errors.count, "error") %> prohibited this question_paper from being saved:</h2>

      <ul>
      <% @question_paper.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :examid %><br>
    <%= f.number_field :examid %>
  </div>
  <div class="field">
    <%= f.label :questionid %><br>
    <%= f.number_field :questionid %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/question_papers/edit.html.erb
<h1>Editing Question Paper</h1>

<%= render 'form' %>

<%= link_to 'Show', @question_paper %> |
<%= link_to 'Back', question_papers_path %>

app/views/question_papers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Question Papers</h1>

<table>
  <thead>
    <tr>
      <th>Examid</th>
      <th>Questionid</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @question_papers.each do |question_paper| %>
      <tr>
        <td><%= question_paper.examid %></td>
        <td><%= question_paper.questionid %></td>
        <td><%= link_to 'Show', question_paper %></td>
        <td><%= link_to 'Edit', edit_question_paper_path(question_paper) %></td>
        <td><%= link_to 'Destroy', question_paper, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Question paper', new_question_paper_path %>

app/views/question_papers/new.html.erb
<h1>New Question Paper</h1>

<%= render 'form' %>

<%= link_to 'Back', question_papers_path %>

app/views/question_papers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Examid:</strong>
  <%= @question_paper.examid %>
</p>

<p>
  <strong>Questionid:</strong>
  <%= @question_paper.questionid %>
</p>

<%= link_to 'Edit', edit_question_paper_path(@question_paper) %> |
<%= link_to 'Back', question_papers_path %>